version: "3.9"
services:
  statsman:
    container_name: statsman
    image: golang:latest
    ports:
      - 8000:8000
    volumes:
      - ./build/:/home/statsman
    working_dir: /home/statsman
    command: ./statsman
